// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Data.EF;

#nullable disable

namespace app.Data.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509145404_AddStartEndTimeToClassSchedules")]
    partial class AddStartEndTimeToClassSchedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("app.Data.EF.Entities.BatchJobExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ErrorTrace")
                        .HasColumnType("text")
                        .HasColumnName("error_trace");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("started_at");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<sbyte?>("TriggeredBy")
                        .HasColumnType("tinyint")
                        .HasColumnName("triggered_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobName");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("batch_job_executions", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.BatchJobItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long>("ExecutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_id");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("target_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("Status");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("batch_job_items", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.BatchJobLock", b =>
                {
                    b.Property<string>("JobName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("locked_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("JobName");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("batch_job_locks", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.ClassEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("class_code");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("current_count");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("MaxStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20)
                        .HasColumnName("max_students");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<sbyte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TeacherId");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.ClassSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<sbyte>("Weekday")
                        .HasColumnType("tinyint")
                        .HasColumnName("weekday");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("ClassId", "Weekday");

                    b.ToTable("class_schedules", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.ClassSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<string>("OnlineLink")
                        .HasColumnType("text")
                        .HasColumnName("online_link");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<sbyte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RoomId");

                    b.HasIndex("SessionDate");

                    b.HasIndex("Status");

                    b.HasIndex("TeacherId");

                    b.ToTable("class_sessions", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.ClassStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AddedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("added_by");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("left_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long?>("RemovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("removed_by");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AddedBy");

                    b.HasIndex("ClassId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("RemovedBy");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("ClassId", "StudentId")
                        .IsUnique();

                    b.ToTable("class_students", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<int?>("TotalSessions")
                        .HasColumnType("int")
                        .HasColumnName("total_sessions");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.CourseCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("course_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsActive = true,
                            Name = "IELTS",
                            Slug = "ielts",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2L,
                            IsActive = true,
                            Name = "TOEIC",
                            Slug = "toeic",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3L,
                            IsActive = true,
                            Name = "TOEFL",
                            Slug = "toefl",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4L,
                            IsActive = true,
                            Name = "English Communication",
                            Slug = "english-communication",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5L,
                            IsActive = true,
                            Name = "Business English",
                            Slug = "business-english",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6L,
                            IsActive = true,
                            Name = "Academic English",
                            Slug = "academic-english",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7L,
                            IsActive = true,
                            Name = "Kids English",
                            Slug = "kids-english",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8L,
                            IsActive = true,
                            Name = "Grammar",
                            Slug = "grammar",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9L,
                            IsActive = true,
                            Name = "Pronunciation",
                            Slug = "pronunciation",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10L,
                            IsActive = true,
                            Name = "Listening",
                            Slug = "listening",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11L,
                            IsActive = true,
                            Name = "Speaking",
                            Slug = "speaking",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12L,
                            IsActive = true,
                            Name = "Reading",
                            Slug = "reading",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13L,
                            IsActive = true,
                            Name = "Writing",
                            Slug = "writing",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14L,
                            IsActive = true,
                            Name = "SAT English",
                            Slug = "sat-english",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15L,
                            IsActive = true,
                            Name = "Cambridge English",
                            Slug = "cambridge-english",
                            SortOrder = 15
                        });
                });

            modelBuilder.Entity("app.Data.EF.Entities.Enrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("completed_at");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount");

                    b.Property<string>("DiscountReason")
                        .HasColumnType("text")
                        .HasColumnName("discount_reason");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("EnrolledBy")
                        .HasColumnType("bigint")
                        .HasColumnName("enrolled_by");

                    b.Property<decimal?>("FinalFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("final_fee");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<decimal?>("TuitionFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tuition_fee");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("EnrolledBy");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Interaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text")
                        .HasColumnName("attachments");

                    b.Property<string>("Channel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Direction")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("direction");

                    b.Property<long?>("LeadId")
                        .HasColumnType("bigint")
                        .HasColumnName("lead_id");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Outcome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("outcome");

                    b.Property<long?>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("StaffId");

                    b.ToTable("interactions", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("final_amount");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("invoice_no");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("paid_amount");

                    b.Property<decimal>("RemainingAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("remaining_amount");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("InvoiceNo")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Lead", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedTo")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_to");

                    b.Property<string>("Campaign")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("campaign");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("converted_at");

                    b.Property<long?>("ConvertedTo")
                        .HasColumnType("bigint")
                        .HasColumnName("converted_to");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Interest")
                        .HasColumnType("text")
                        .HasColumnName("interest");

                    b.Property<string>("LostReason")
                        .HasColumnType("text")
                        .HasColumnName("lost_reason");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<sbyte?>("Source")
                        .HasColumnType("tinyint")
                        .HasColumnName("source");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("ConvertedTo");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<long?>("CollectedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("collected_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<sbyte?>("Method")
                        .HasColumnType("tinyint")
                        .HasColumnName("method");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("paid_at");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("transaction_ref");

                    b.HasKey("Id");

                    b.HasIndex("CollectedBy");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaidAt");

                    b.HasIndex("Status");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Facilities")
                        .HasColumnType("text")
                        .HasColumnName("facilities");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Staff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<sbyte?>("Department")
                        .HasColumnType("tinyint")
                        .HasColumnName("department");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("manager_id");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("position");

                    b.Property<string>("StaffCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("staff_code");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StaffCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<long?>("AssignedStaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_staff_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("enrolled_at");

                    b.Property<sbyte?>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ParentEmail")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("parent_email");

                    b.Property<string>("ParentName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("parent_name");

                    b.Property<string>("ParentPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("parent_phone");

                    b.Property<sbyte?>("Source")
                        .HasColumnType("tinyint")
                        .HasColumnName("source");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("student_code");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedTo")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("done_at");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("due_at");

                    b.Property<sbyte>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)2)
                        .HasColumnName("priority");

                    b.Property<long?>("RelatedLeadId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_lead_id");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RelatedLeadId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<sbyte?>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("app.Data.EF.Entities.BatchJobItem", b =>
                {
                    b.HasOne("app.Data.EF.Entities.BatchJobExecution", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("app.Data.EF.Entities.ClassEntity", b =>
                {
                    b.HasOne("app.Data.EF.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("app.Data.EF.Entities.ClassSchedule", b =>
                {
                    b.HasOne("app.Data.EF.Entities.ClassEntity", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Data.EF.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("app.Data.EF.Entities.ClassSession", b =>
                {
                    b.HasOne("app.Data.EF.Entities.ClassEntity", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("app.Data.EF.Entities.ClassStudent", b =>
                {
                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AddedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.ClassEntity", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("app.Data.EF.Entities.Enrollment", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RemovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("app.Data.EF.Entities.Course", b =>
                {
                    b.HasOne("app.Data.EF.Entities.CourseCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Enrollment", b =>
                {
                    b.HasOne("app.Data.EF.Entities.ClassEntity", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("app.Data.EF.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("EnrolledBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("app.Data.EF.Entities.Interaction", b =>
                {
                    b.HasOne("app.Data.EF.Entities.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Invoice", b =>
                {
                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.Enrollment", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("app.Data.EF.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("app.Data.EF.Entities.Lead", b =>
                {
                    b.HasOne("app.Data.EF.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("ConvertedTo")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("app.Data.EF.Entities.Payment", b =>
                {
                    b.HasOne("app.Data.EF.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("CollectedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("app.Data.EF.Entities.Staff", b =>
                {
                    b.HasOne("app.Data.EF.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("app.Data.EF.Entities.Student", b =>
                {
                    b.HasOne("app.Data.EF.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("app.Data.EF.Entities.TaskItem", b =>
                {
                    b.HasOne("app.Data.EF.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("app.Data.EF.Entities.Lead", null)
                        .WithMany()
                        .HasForeignKey("RelatedLeadId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
